/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Curator's Folio & Commonplace palette (ported from Stitch DESIGN.md)
        "tertiary-fixed": "#bceed3",
        "on-background": "#1d1b19",
        surface: "#fef8f3",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#44474a",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#63917a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdbcf",
        "tertiary-container": "#002618",
        tertiary: "#000b05",
        "error-container": "#ffdad6",
        "on-secondary-container": "#6f2000",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#a1d1b8",
        outline: "#75777a",
        primary: "#06080a",
        background: "#fef8f3",
        "secondary-fixed-dim": "#ffb59c",
        "surface-container-highest": "#e6e2dd",
        "on-primary-fixed-variant": "#454749",
        "on-secondary-fixed": "#390c00",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c6c6c9",
        "on-surface": "#1d1b19",
        "surface-container": "#f2ede8",
        "on-primary-container": "#86878a",
        secondary: "#a23e18",
        "on-tertiary-fixed-variant": "#224f3c",
        "primary-fixed": "#e2e2e5",
        "surface-tint": "#5d5e61",
        "surface-container-low": "#f8f3ee",
        "surface-bright": "#fef8f3",
        "on-primary-fixed": "#1a1c1e",
        "inverse-primary": "#c6c6c9",
        "secondary-container": "#fe8357",
        "surface-dim": "#ded9d4",
        "inverse-surface": "#32302d",
        "surface-container-high": "#ece7e2",
        "primary-container": "#1e2022",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f5f0eb",
        "on-tertiary-fixed": "#002114",
        "surface-variant": "#e6e2dd",
        "on-secondary-fixed-variant": "#822801",
        "outline-variant": "#c5c6ca",
        // Named brand accents used directly in the mockups
        ink: "#1e2022",
        terracotta: "#a23e18",
        "moss-deep": "#182e23",
        "moss-mid": "#234233",
        "moss-line": "#244233",
        "moss-text": "#e8f2ec",
        "moss-muted": "#98baa7",
        "moss-bright": "#52c185",
        "moss-pale": "#bceed3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "gutter-desktop": "2rem",
        "space-2xs": "0.25rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-sm": "0.75rem",
        "space-3xl": "4.5rem",
        "space-xs": "0.5rem",
        "content-reading-width": "46rem",
        "content-catalog-width": "76rem",
      },
      fontFamily: {
        serif: ["Newsreader", "serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      maxWidth: {
        catalog: "76rem",
        reading: "46rem",
      },
    },
  },
  plugins: [],
};
